version: '2'
services:
  base-bot:
    build: ./
    volumes:
      - .:/go/src/github.com/disiqueira/MySlackBot
    environment:
      MSB_SLACKTOKEN: ${SLACK_TOKEN}

  choose:
    extends: base-bot
    environment:
      APP_FUN: "-cmd=choose"

  weather:
    extends: base-bot
    environment:
      APP_FUN: "-cmd=weather"
      MSB_OPENWEATHERTOKEN: ${OPEN_WEATHER_TOKEN}

  lastfm:
    extends: base-bot
    environment:
      APP_FUN: "-cmd=lastfm"
      MSB_LASTFMTOKEN: ${LASTFM_TOKEN}

  wolfram:
    extends: base-bot
    environment:
      APP_FUN: "-cmd=wolfram"
      MSB_WOLFRAMTOKEN: ${WOLFRAM_TOKEN}

  pokemon:
    extends: base-bot
    environment:
      APP_FUN: "-cmd=pokemon"

  shrug:
    extends: base-bot
    environment:
      APP_FUN: "-cmd=shrug"

